spring:
  rabbitmq:
    host: @RABBITMQ_HOST@
    port: @RABBITMQ_PORT@
    username: @RABBITMQ_USERNAME@
    password: @RABBITMQ_PASSWORD@

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://@DB_HOST@:@DB_PORT@/@DB_NAME@
    username: @DB_USERNAME@
    password: @DB_PASSWORD@

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json