server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
  tomcat:
    accept-count: 100
    max-connections: 8192
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

spring:
  application:
    name: shop-api

  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: @RABBITMQ_HOST@
    port: @RABBITMQ_PORT@
    username: @RABBITMQ_USERNAME@
    password: @RABBITMQ_PASSWORD@

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://@DB_HOST@:@DB_PORT@/@DB_NAME@
    username: @DB_USERNAME@
    password: @DB_PASSWORD@
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379              # Redis 서버 포트
      database: 0             # Redis 데이터베이스 인덱스
      timeout: 5000          # 연결 타임아웃 (밀리초)
      lettuce: # Lettuce 클라이언트 설정
        pool:
          max-active: 8      # 최대 연결 수
          max-idle: 8        # 최대 유휴 연결 수
          min-idle: 0        # 최소 유휴 연결 수
          max-wait: -1       # 최대 대기 시간 (-1은 무제한)

app:
  security:
    jwt:
      public-paths:
        - "/open-api/**"
        - "/swagger-ui/**"
        - "/v1/api-docs/**"
        - "/error"
        - "/open-api/health"

      admin-paths:
        - "/api/admin/**"
        - "/api/management/**"

# Casbin 설정 (공식 문서 기준)
casbin:
  # Casbin 활성화 (기본값: true)
  enableCasbin: true
  # 분산 Enforcer 사용 (멀티 인스턴스 환경)
  useDistributedEnforcer: true
  # 자동 정책 저장 활성화
  autoSave: true
  # 저장소 타입: jdbc (PostgreSQL 사용)
  storeType: jdbc
  # PostgreSQL용 커스텀 테이블명
  tableName: casbin_rule
  # 데이터소스 초기화 정책 (테이블 자동 생성)
  initializeSchema: create
  # 모델 설정 파일 위치
  model: classpath:casbin/model.conf
  # 기본 RBAC 모델 사용 (모델 파일이 없을 경우)
  useDefaultModelIfModelNotSetting: true
  # Watcher 메커니즘 활성화 (멀티 인스턴스 동기화)
  enableWatcher: true
  # Watcher 타입: Redis 사용
  watcherType: redis
  # Spring 트랜잭션 지원
  watcherTxSupport: true
  # 예외 설정
  exception:
    removePolicyFailed: false


token:
  secret:
    key: @JWT_SECRET_KEY@
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12


springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: true
    path: /index.html
  default-produces-media-type: application/json
  default-consumes-media-type: application/json


logging:
  level:
    root: INFO