spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://@DB_HOST@:@DB_PORT@/@DB_NAME@
    username: @DB_USERNAME@
    password: @DB_PASSWORD@